import java.util.*;
class copy {    
    public static void main(String[] args) {
      Scanner abc = new Scanner(System.in);

      System.out.println("                                            .....Al Shifa Pharmacy....                                ");

      System.out.println("Patient Account Number");
      int number1=abc.nextInt();
      abc.nextLine();
      // System.out.println(number1);
      System.out.println("Admission Date");
      String admission=abc.nextLine();
      // System.out.println(admission);
      System.out.println("Discharge Date");
      String discharge=abc.nextLine();
      // System.out.println(discharge);
      System.out.println("Patient Name");
      String patientName=abc.nextLine();
      // System.out.println(patientName);
      System.out.println("Diagnosis");
      String diagnosis=abc.nextLine();
      // System.out.println(diagnosis);
      System.out.println("_________________________________");
      System.out.println("Bill Issue Date");
      String issueDate=abc.nextLine();
      // System.out.println(issueDate);
      System.out.println("Bill Issue Day");
      String issueDay=abc.nextLine();
      // System.out.println(issueDay);    
      System.out.println("________________________________________________");
      System.out.println("              Enter Medicine 01 Detail          ");
      System.out.print("Enter Medicine 1 name: ");
      String name1=abc.nextLine();
      System.out.print("Enter Medicine 1 code: ");
      int code1=abc.nextInt();
      System.out.print("Enter Medicine 1 price: ");
      int price1=abc.nextInt();
      abc.nextLine();
      System.out.println("________________________________________________");
      System.out.println("              Enter Medicine 02 Detail          ");
      System.out.print("Enter Medicine 2 name: ");
      String name2=abc.nextLine();
      System.out.print("Enter Medicine 2 code: ");
      int code2=abc.nextInt();
      System.out.print("Enter Medicine 2 price: ");
      int price2=abc.nextInt();
      abc.nextLine();
      System.out.println("_________________________________________________");
      System.out.println("            Enter Medicine 03 Detail             ");
      System.out.print("Enter Medicine 3 name: ");
      String name3=abc.nextLine();
      System.out.print("Enter Medicine 3 code: ");
      int code3=abc.nextInt();
      System.out.print("Enter Medicine 3 price: ");
      int price3=abc.nextInt();
      abc.nextLine();
      System.out.println("_______________________________________________________");
      System.out.println("Medicine                Code                Price      ");
      System.out.println("_______________________________________________________");
      System.out.printf("%s                   %d                  %d        \n",name1, code1, price1);
      System.out.printf("%s                   %d                  %d        \n",name2, code2, price2);
      System.out.printf("%s                   %d                  %d        \n",name3, code3, price3);
      System.out.println("-------------------------------------------------------");  
      int Total=price1+price2+price3;
      System.out.println("                                         TOTAL PRICE= "+Total);
      System.out.println("*************************************************************");
      System.out.println("                   Employees Detail                          ");
      System.out.println("*************************************************************");
      System.out.println("_____________________________________________________________");
      System.out.println("                   Employee 01 Detail                        ");
      System.out.println("_____________________________________________________________");
      System.out.print("Enter Employee ID: ");
      int id1=abc.nextInt();
      abc.nextLine();
      System.out.print("Enter Employee Name: ");
      String employee1=abc.nextLine();
      System.out.print("Enter Employee Address: ");
      String address1=abc.nextLine();
      System.out.print("Working Hours per day: ");
      double working1=abc.nextDouble();
      abc.nextLine();
      System.out.print("Salary per Hour: ");
      double perhour1=abc.nextDouble();
      abc.nextLine();
      double salaryperday1=working1*perhour1;
      System.out.print("Salary per day: "+salaryperday1);
      double salarypermonth1=salaryperday1*30;
      System.out.println("Salary per month: "+salarypermonth1);
      System.out.println("_____________________________________________________________");
      System.out.println("                      Employee 02 Detail                     ");
      System.out.println("_____________________________________________________________");
      System.out.print("Enter Employee ID: ");
      int id2=abc.nextInt();
      abc.nextLine();
      System.out.print("Enter Employee Name: ");
      String employee2=abc.nextLine();
      System.out.print("Enter Employee Address: ");
      String address2=abc.nextLine();
      System.out.print("Working Hours per day: ");
      double working2=abc.nextDouble();
      abc.nextLine();
      System.out.print("Salary per Hour: ");
      double perhour2=abc.nextDouble();
      abc.nextLine();
      double salaryperday2=working2*perhour2;
      System.out.println("Salary per day: "+salaryperday2); 
      double salarypermonth2=salaryperday2*30;
      System.out.println("Salary per month: "+salarypermonth2);
      System.out.println("____________________________________________________________");
      System.out.println("                      Employee 03 Detail                     ");
      System.out.println("_____________________________________________________________");
      System.out.print("Enter Employee ID: ");
      int id3=abc.nextInt();
      abc.nextLine();
      System.out.print("Enter Employee Name: ");
      String employee3=abc.nextLine();
      System.out.print("Enter Employee Address: ");
      String address3=abc.nextLine();
      System.out.print("Working Hours per day: ");
      double working3=abc.nextDouble();
      abc.nextLine();
      System.out.print("Salary per Hour: ");
      double perhour3=abc.nextDouble();
      abc.nextLine();
      double salaryperday3=working3*perhour3;
      System.out.println("Salary per day: "+salaryperday3);
      double salarypermonth3=salaryperday3*30;
      System.out.println("Salary per month: "+salarypermonth3);
      System.out.println("__________________________________________________________________________________________________________________");
      System.out.println("Employee ID        Name             Address             Working Hours/Day        Salary/Day         Salary/Month  ");
      System.out.println("__________________________________________________________________________________________________________________");
      System.out.printf("%d              %s              %s                   %f                        %f                    %f \n",id1, employee1, address1, working1,salaryperday1,salarypermonth1);
      System.out.printf("%d              %s              %s                   %f                       %f                    %f\n",id2, employee2, address2, working2,salaryperday2,salarypermonth2);
      System.out.printf("%d              %s              %s                   %f                       %f                    %f\n",id3, employee3, address3, working3,salaryperday3,salarypermonth3);  

}
}
