import java.util.*;
class copy {    
    public static void main(String[] args) {
      Scanner abc = new Scanner(System.in);
      System.out.println("                                            .....Al Shifa Pharmacy....                                ");
      System.out.println("Menue");
      System.out.println("1.Patient Detail");
      System.out.println("2.Medicines Detail");
      System.out.println("3.Total Bill");
      System.out.println("4.Employees Detail");
      System.out.println("5.Overall Employee Data");
      String name1="";
      String name2="";
      String name3="";
      int code1=0;
      int code2=0;
      int code3=0;
      int price1=0;
      int price2=0;
      int price3=0;
      int id1=0;
      int id2=0;
      int id3=0;
      String employee1="";
      String employee2="";
      String employee3="";
      String address1="";
      String address2="";
      String address3="";
      double working1=0;
      double working2=0;
      double working3=0;
      double perhour1=0;
      double perhour2=0;
      double perhour3=0;
      double salaryperday1=0;
      double salaryperday2=0;
      double salaryperday3=0;
      double salarypermonth1=0;
      double salarypermonth2=0;
      double salarypermonth3=0;
      int choice=abc.nextInt();  
      switch(choice){
      case 1:
      System.out.println("Patient Account Number");
      int number1=abc.nextInt();
      abc.nextLine();
      System.out.println(number1);
      System.out.println("Admission Date");
      String admission=abc.nextLine();
      System.out.println(admission);
      System.out.println("Discharge Date");
      String discharge=abc.nextLine();
      System.out.println(discharge);
      System.out.println("Patient Name");
      String patientName=abc.nextLine();
      System.out.println(patientName);
      System.out.println("Diagnosis");
      String diagnosis=abc.nextLine();
      System.out.println(diagnosis);
      System.out.println("_________________________________");
      System.out.println("Bill Issue Date");
      String issueDate=abc.nextLine();
      System.out.println(issueDate);
      System.out.println("Bill Issue Day");
      String issueDay=abc.nextLine();
      System.out.println(issueDay);
      case 2:  
      System.out.println("________________________________________________");
      System.out.println("              Enter Medicine 01 Detail          ");
      System.out.print("Enter Medicine 1 name: ");
      name1=abc.nextLine();
      System.out.print("Enter Medicine 1 code: ");
      code1=abc.nextInt();
      System.out.print("Enter Medicine 1 price: ");
      price1=abc.nextInt();
      abc.nextLine();
      System.out.println("________________________________________________");
      System.out.println("              Enter Medicine 02 Detail          ");
      System.out.print("Enter Medicine 2 name: ");
      name2=abc.nextLine();
      System.out.print("Enter Medicine 2 code: ");
      code2=abc.nextInt();
      System.out.print("Enter Medicine 2 price: ");
      price2=abc.nextInt();
      abc.nextLine();
      System.out.println("_________________________________________________");
      System.out.println("            Enter Medicine 03 Detail             ");
      System.out.print("Enter Medicine 3 name: ");
      name3=abc.nextLine();
      System.out.print("Enter Medicine 3 code: ");
      code3=abc.nextInt();
      System.out.print("Enter Medicine 3 price: ");
      price3=abc.nextInt();
      abc.nextLine();
      break;
      case 3:
      System.out.println("_______________________________________________________");
      System.out.println("Medicine                Code                Price      ");
      System.out.println("_______________________________________________________");
      System.out.printf("%s                   %d                  %d        \n",name1, code1, price1);
      System.out.printf("%s                   %d                  %d        \n",name2, code2, price2);
      System.out.printf("%s                   %d                  %d        \n",name3, code3, price3);
      System.out.println("-------------------------------------------------------");  
      int Total =price1 + price2 + price3;
      System.out.println("                                         TOTAL PRICE= "+Total);
      break;
      case 4:
      System.out.println("*************************************************************");
      System.out.println("                   Employees Detail                          ");
      System.out.println("*************************************************************");
      System.out.println("_____________________________________________________________");
      System.out.println("                   Employee 01 Detail                        ");
      System.out.println("_____________________________________________________________");
      System.out.print("Enter Employee ID: ");
      id1=abc.nextInt();
      abc.nextLine();
      System.out.print("Enter Employee Name: ");
      employee1=abc.nextLine();
      System.out.print("Enter Employee Address: ");
      address1=abc.nextLine();
      System.out.print("Working Hours per day: ");
      working1=abc.nextDouble();
      abc.nextLine();
      System.out.print("Salary per Hour: ");
      perhour1=abc.nextDouble();
      abc.nextLine();
      salaryperday1=working1*perhour1;
      System.out.print("Salary per day: "+salaryperday1);
      salarypermonth1=salaryperday1*30;
      System.out.println("Salary per month: "+salarypermonth1);
      System.out.println("_____________________________________________________________");
      System.out.println("                      Employee 02 Detail                     ");
      System.out.println("_____________________________________________________________");
      System.out.print("Enter Employee ID: ");
      id2=abc.nextInt();
      abc.nextLine();
      System.out.print("Enter Employee Name: ");
      employee2=abc.nextLine();
      System.out.print("Enter Employee Address: ");
      address2=abc.nextLine();
      System.out.print("Working Hours per day: ");
      working2=abc.nextDouble();
      abc.nextLine();
      System.out.print("Salary per Hour: ");
      perhour2=abc.nextDouble();
      abc.nextLine();
      salaryperday2=working2*perhour2;
      System.out.println("Salary per day: "+salaryperday2); 
      salarypermonth2=salaryperday2*30;
      System.out.println("Salary per month: "+salarypermonth2);
      System.out.println("____________________________________________________________");
      System.out.println("                      Employee 03 Detail                     ");
      System.out.println("_____________________________________________________________");
      System.out.print("Enter Employee ID: ");
      id3=abc.nextInt();
      abc.nextLine();
      System.out.print("Enter Employee Name: ");
      employee3=abc.nextLine();
      System.out.print("Enter Employee Address: ");
      address3=abc.nextLine();
      System.out.print("Working Hours per day: ");
      working3=abc.nextDouble();
      abc.nextLine();
      System.out.print("Salary per Hour: ");
      perhour3=abc.nextDouble();
      abc.nextLine();
      salaryperday3=working3*perhour3;
      System.out.println("Salary per day: "+salaryperday3);
      salarypermonth3=salaryperday3*30;
      System.out.println("Salary per month: "+salarypermonth3);
      break;
      case 5:
      System.out.println("__________________________________________________________________________________________________________________");
      System.out.println("Employee ID        Name             Address             Working Hours/Day        Salary/Day         Salary/Month  ");
      System.out.println("__________________________________________________________________________________________________________________");
      System.out.printf("%d              %s              %s                   %f                        %f                    %f \n",id1, employee1, address1, working1,salaryperday1,salarypermonth1);
      System.out.printf("%d              %s              %s                   %f                       %f                    %f\n",id2, employee2, address2, working2,salaryperday2,salarypermonth2);
      System.out.printf("%d              %s              %s                   %f                       %f                    %f\n",id3, employee3, address3, working3,salaryperday3,salarypermonth3); 
      break;
      }
    }
  }


